version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
      
  pre_build:
    commands:
      - pwd
      - cd /efs
      - ls /efs
      - cd /efs/source_code
      
  build:
    commands:
      - cd /efs/source_code
      - . build/envsetup.sh
      - lunch rpi4-eng
      - make ramdisk systemimage vendorimage -j10

  post_build:
    commands:
      - echo "Sono in Post Build"
      - ls 
      - ls /efs/source_code
      
      
