version: 0.2

phases:
  install:
    runtime-versions:
      android: 29
      
  pre_build:
    commands:
      - pwd
      - cd /efs
      - ls /efs
      - cd /efs/kernel_source
      
  build:
    commands:
      - cd /efs/kernel_source
      - build/build.sh

  post_build:
    commands:
      - echo "Sono in Post Build"
      - ls 
      - ls /efs/kernel_source
      
      
artifacts:
  files:
   # - '**/*.tar'
      
